# -*- coding: utf-8 -*-
"""Banking _bot loading_model _qlora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uD-dKd9kE0Mgrz4NtgaXqub40y8ZMlgw
"""

# pip install transformers datasets peft trl accelerate bitsandbytes

# finetuning the qwen instruct model with custom dataset using Qlora

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

# 4-bit quantization config

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",   # best for LLMs
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16
)

# qwen model

model_name = "Qwen/Qwen2.5-3B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

# lora traiinable adapaters to layers

from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

model.save_pretrained("banking-lora-adapter")
tokenizer.save_pretrained("banking-lora-adapter")

# 1. Mount your Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Define your folder path
save_directory = "/content/drive/MyDrive/banking_chatbot_lora_init"

# 3. Save the adapter weights and the tokenizer
model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

print(f"LoRA structure safely saved to: {save_directory}")

